/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.Customer;
import Controller.Order;
import Controller.Product;
import Model.OrderRepository;
import Model.ProductModel;
import Model.UserRepository;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AbdelRahman Badran , Madoma Diallo
 */

public class AdminPanel extends javax.swing.JFrame {
    DefaultTableModel tableModelProduct = new DefaultTableModel();
    DefaultTableModel tableModelOrder = new DefaultTableModel();
    private ProductModel pro_Model = new ProductModel();
    private OrderRepository orderModel = new OrderRepository();
    Order orderControl = new Order();
    ManageProduct manageProduct;
    OrderInformation orderInformation;

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
         try {
             //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
             try {
                 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                     if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                     }
                 }
             } catch (ClassNotFoundException ex) {
                 java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             } catch (InstantiationException ex) {
                 java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             } catch (IllegalAccessException ex) {
                 java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                 java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             }
             //</editor-fold>
             initComponents();
             this.repaint();
             pro_Model.importProducts(ProductTable,tableModelProduct);
             orderModel.importOrders(orderTable, tableModelOrder);
             //orderControl.populateManageOrderTable(tableModelOrder,orderTable);
             manageProductDetails();
             manageOrders();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amindPanel = new javax.swing.JPanel();
        adminUpPanel = new javax.swing.JPanel();
        AdminPanelLabel = new javax.swing.JLabel();
        AdminPanelIcon = new javax.swing.JLabel();
        adminSearchFld = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        adminLayeredPanel = new javax.swing.JLayeredPane();
        manageProductPanel = new javax.swing.JPanel();
        ProductScrollable = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        manageOrderPanel = new javax.swing.JPanel();
        orderScrollable = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        adminSidePanel = new javax.swing.JPanel();
        addProductBtn = new javax.swing.JButton();
        maanageProductBtn = new javax.swing.JButton();
        manageOrdersBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        accountSettingsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amindPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminUpPanel.setBackground(new java.awt.Color(51, 0, 51));
        adminUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminPanelLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        AdminPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanelLabel.setText("Administrator Panel");
        AdminPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminPanelLabelMouseClicked(evt);
            }
        });
        adminUpPanel.add(AdminPanelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 15, -1, 33));

        AdminPanelIcon.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8_Admin_48px.png"))); // NOI18N
        adminUpPanel.add(AdminPanelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 15, -1, 53));

        adminSearchFld.setToolTipText("Search Products...");
        adminSearchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSearchFldActionPerformed(evt);
            }
        });
        adminUpPanel.add(adminSearchFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 252, 29));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        adminUpPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        amindPanel.add(adminUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 80));

        adminLayeredPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminLayeredPanel.setLayout(new java.awt.CardLayout());

        manageProductPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageProductPanel.setMinimumSize(new java.awt.Dimension(1020, 660));
        manageProductPanel.setPreferredSize(new java.awt.Dimension(1060, 610));
        manageProductPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductScrollable.setBackground(new java.awt.Color(255, 255, 255));

        ProductTable.setAutoCreateRowSorter(true);
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        ProductScrollable.setViewportView(ProductTable);

        manageProductPanel.add(ProductScrollable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        adminLayeredPanel.add(manageProductPanel, "card2");

        manageOrderPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageOrderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderScrollable.setBackground(new java.awt.Color(255, 255, 255));

        orderTable.setAutoCreateRowSorter(true);
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Caustomer Name", "Total Amount", "Order Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        orderScrollable.setViewportView(orderTable);

        manageOrderPanel.add(orderScrollable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        adminLayeredPanel.add(manageOrderPanel, "card3");

        amindPanel.add(adminLayeredPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 1060, 610));

        adminSidePanel.setBackground(new java.awt.Color(51, 0, 51));
        adminSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addProductBtn.setBackground(new java.awt.Color(51, 0, 51));
        addProductBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        addProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-plus-48.png"))); // NOI18N
        addProductBtn.setText("Add Product");
        addProductBtn.setBorderPainted(false);
        addProductBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductBtn.setHideActionText(true);
        addProductBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addProductBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        addProductBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });
        adminSidePanel.add(addProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 150, 90));

        maanageProductBtn.setBackground(new java.awt.Color(51, 0, 51));
        maanageProductBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        maanageProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        maanageProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-box-48.png"))); // NOI18N
        maanageProductBtn.setText("Manage Products");
        maanageProductBtn.setBorderPainted(false);
        maanageProductBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maanageProductBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maanageProductBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        maanageProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maanageProductBtnActionPerformed(evt);
            }
        });
        adminSidePanel.add(maanageProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 90));

        manageOrdersBtn.setBackground(new java.awt.Color(51, 0, 51));
        manageOrdersBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        manageOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageOrdersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-online-store-48.png"))); // NOI18N
        manageOrdersBtn.setText("Manage Orders");
        manageOrdersBtn.setBorderPainted(false);
        manageOrdersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageOrdersBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageOrdersBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageOrdersBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersBtnActionPerformed(evt);
            }
        });
        adminSidePanel.add(manageOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 90));

        LogoutBtn.setBackground(new java.awt.Color(51, 0, 51));
        LogoutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/Exit.png"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setBorderPainted(false);
        LogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogoutBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        adminSidePanel.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 150, 90));

        accountSettingsBtn.setBackground(new java.awt.Color(51, 0, 51));
        accountSettingsBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        accountSettingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        accountSettingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-administrative-tools-48.png"))); // NOI18N
        accountSettingsBtn.setText("Account Settings");
        accountSettingsBtn.setBorderPainted(false);
        accountSettingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountSettingsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountSettingsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        accountSettingsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        accountSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsBtnActionPerformed(evt);
            }
        });
        adminSidePanel.add(accountSettingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 150, 90));

        amindPanel.add(adminSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 610));

        getContentPane().add(amindPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 694));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminSearchFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSearchFldActionPerformed

    }//GEN-LAST:event_adminSearchFldActionPerformed

    private void AdminPanelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminPanelLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPanelLabelMouseClicked

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        int logout= JOptionPane.showConfirmDialog(null, "Sure you want to Logout?", "Choose", JOptionPane.YES_NO_OPTION); 
        if (logout == JOptionPane.YES_OPTION) {
            this.dispose();
            MainPageView frame = new MainPageView();
            frame.setVisible(true);
            }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtnActionPerformed
        this.dispose();
        AddNewProduct nextFrame = new AddNewProduct(this,true,tableModelProduct);
        nextFrame.setVisible(true);
    }//GEN-LAST:event_addProductBtnActionPerformed

    private void manageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersBtnActionPerformed
        manageProductPanel.setVisible(false);
        manageOrderPanel.setVisible(true);
    }//GEN-LAST:event_manageOrdersBtnActionPerformed

    private void accountSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsBtnActionPerformed
        this.dispose();
        AdminAccountSettings newFrame;
        try {
            newFrame = new AdminAccountSettings();
             newFrame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_accountSettingsBtnActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        DefaultTableModel productSearch = (DefaultTableModel) ProductTable.getModel();
        DefaultTableModel orderSearch = (DefaultTableModel) orderTable.getModel();
        
        String searchPhrase = adminSearchFld.getText();

        TableRowSorter<DefaultTableModel> sort = new TableRowSorter<> (productSearch);
        ProductTable.setRowSorter(sort);
        sort.setRowFilter(RowFilter.regexFilter(searchPhrase));
        
        TableRowSorter<DefaultTableModel> sorting = new TableRowSorter<> (orderSearch);
        orderTable.setRowSorter(sorting);
        sorting.setRowFilter(RowFilter.regexFilter(searchPhrase));
    }//GEN-LAST:event_searchButtonActionPerformed

    private void maanageProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maanageProductBtnActionPerformed
        manageOrderPanel.setVisible(false);
        manageProductPanel.setVisible(true);
    }//GEN-LAST:event_maanageProductBtnActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        manageProduct.setVisible(true);
    }//GEN-LAST:event_ProductTableMouseClicked

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
       orderInformation.setVisible(true);
    }//GEN-LAST:event_orderTableMouseClicked

    public void manageProductDetails(){
        AdminPanel.productsListner searchListner = new AdminPanel.productsListner();
        ProductTable.getSelectionModel().addListSelectionListener(searchListner);
    }

    public void manageOrders(){
        AdminPanel.ordersListener orderDetail = new AdminPanel.ordersListener();
        orderTable.getSelectionModel().addListSelectionListener(orderDetail);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminPanelIcon;
    private javax.swing.JLabel AdminPanelLabel;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JScrollPane ProductScrollable;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton accountSettingsBtn;
    private javax.swing.JButton addProductBtn;
    private javax.swing.JLayeredPane adminLayeredPanel;
    private javax.swing.JTextField adminSearchFld;
    private javax.swing.JPanel adminSidePanel;
    private javax.swing.JPanel adminUpPanel;
    private javax.swing.JPanel amindPanel;
    private javax.swing.JButton maanageProductBtn;
    private javax.swing.JPanel manageOrderPanel;
    private javax.swing.JButton manageOrdersBtn;
    private javax.swing.JPanel manageProductPanel;
    private javax.swing.JScrollPane orderScrollable;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    private class productsListner implements ListSelectionListener{
        @Override
        public void valueChanged(ListSelectionEvent event) {
            
            
            if(ProductTable.getSelectedRow()!= -1){
                 String productName = ProductTable.getValueAt(ProductTable.getSelectedRow(), 0).toString();
                 Product search = new Product();
                 Product selectedProduct = search.searchProductInformation(productName);
                 
                 manageProduct = new ManageProduct(selectedProduct);
            }
           
        }
    }

    private class ordersListener implements ListSelectionListener{
        @Override
        public void valueChanged(ListSelectionEvent event) {

            if(orderTable.getSelectedRow()!= -1){
            Customer orderFromCustomer = new Customer();
            UserRepository userRepo = new UserRepository();

            int orderID = Integer.parseInt(orderTable.getValueAt(orderTable.getSelectedRow(), 0).toString());
            String customerName =  orderTable.getValueAt(orderTable.getSelectedRow(), 1).toString();
            Order selectedOrder = orderControl.searchOrderInformation(orderID);

                 //checks to see if it is not reviewed
                 if (selectedOrder.getOrderStatus().equals("Not Reviewed")) {
                     try {
                     orderFromCustomer = userRepo.searchCustomerWithName(customerName);
                    
                    }catch (Exception ex) {
                     Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                     
                  orderInformation = new OrderInformation(selectedOrder, orderFromCustomer);
                }
                else{
                    //displays the status of the selected order
                    JOptionPane.showMessageDialog(null, "This order has already been " + selectedOrder.getOrderStatus());
                    }
                }
             }
         }
}
