/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Customer;
import java.awt.Window;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author AbdelRahman Badran , Madoma Diallo 
 */
@SuppressWarnings("serial")
public class CustomerAccountSettings extends javax.swing.JDialog {
      private Customer loggedCustomer = new Customer();
      private Customer updatedCustomer;
    /**
     * Creates new form CustomerAccountSettings
     * @param parent
     * @param modal
     * @param customer
     */
    public CustomerAccountSettings(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        this.loggedCustomer = customer;
        updatedCustomer = this.loggedCustomer.copyOfCustomer();
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> 
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
         //</editor-fold>
        initComponents();
        
        customerIDFld.setText(Integer.toString(loggedCustomer.getId()));
        usernameTxtFld.setText(loggedCustomer.getName());
        contactTxtFld.setText(loggedCustomer.getContact());
        emailTxtFld.setText(loggedCustomer.getEmail());
        //sets comboBox value
        addressComboBox.getModel().setSelectedItem(loggedCustomer.getAddress());
        passFld.setText(loggedCustomer.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerSettingsUpPanel = new javax.swing.JPanel();
        customerSettingsIcon = new javax.swing.JLabel();
        profileSettingsLbl = new javax.swing.JLabel();
        customerNameLbl = new javax.swing.JLabel();
        csutomerIdLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        contactNumberLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        passFld = new javax.swing.JPasswordField();
        newPassFld = new javax.swing.JPasswordField();
        confirmPassFld = new javax.swing.JPasswordField();
        passwordLbl = new javax.swing.JLabel();
        NewPassLbl = new javax.swing.JLabel();
        conformPassLbl = new javax.swing.JLabel();
        SettingsSep = new javax.swing.JSeparator();
        updateDetailsBtn = new javax.swing.JButton();
        addressLbl = new javax.swing.JLabel();
        addressComboBox = new javax.swing.JComboBox<>();
        customerIDFld = new javax.swing.JTextField();
        contactTxtFld = new javax.swing.JTextField();
        usernameTxtFld = new javax.swing.JTextField();
        emailTxtFld = new javax.swing.JTextField();
        showPasswordcheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerSettingsUpPanel.setBackground(new java.awt.Color(51, 0, 51));
        customerSettingsUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerSettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-services-48.png"))); // NOI18N
        customerSettingsUpPanel.add(customerSettingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        profileSettingsLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        profileSettingsLbl.setForeground(new java.awt.Color(255, 255, 255));
        profileSettingsLbl.setText("Profile Settings");
        customerSettingsUpPanel.add(profileSettingsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        customerNameLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        customerNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        customerSettingsUpPanel.add(customerNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 40, 60, -1));

        getContentPane().add(customerSettingsUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 80));

        csutomerIdLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        csutomerIdLbl.setText("Customer Id");
        getContentPane().add(csutomerIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        usernameLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        usernameLbl.setText("Username");
        getContentPane().add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        contactNumberLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        contactNumberLbl.setText("Contact Number");
        getContentPane().add(contactNumberLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        emailLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        emailLbl.setText("Email");
        getContentPane().add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        passFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        passFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFldActionPerformed(evt);
            }
        });
        getContentPane().add(passFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 140, -1));

        newPassFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        newPassFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassFldActionPerformed(evt);
            }
        });
        getContentPane().add(newPassFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 140, -1));

        confirmPassFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        confirmPassFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPassFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, -1));

        passwordLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        passwordLbl.setText(" Password");
        getContentPane().add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        NewPassLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        NewPassLbl.setText("New Password");
        getContentPane().add(NewPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        conformPassLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        conformPassLbl.setText("Confirm Password");
        getContentPane().add(conformPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        SettingsSep.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(SettingsSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 510, 10));

        updateDetailsBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateDetailsBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        updateDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-update-48.png"))); // NOI18N
        updateDetailsBtn.setText("Update");
        updateDetailsBtn.setBorderPainted(false);
        updateDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateDetailsBtn.setFocusPainted(false);
        updateDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateDetailsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 100, 80));

        addressLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        addressLbl.setText("Address");
        getContentPane().add(addressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        addressComboBox.setBackground(new java.awt.Color(255, 255, 255));
        addressComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kuala Lumpur", "Seberang Perai", "Kajang", "Klang", "Subang Jaya", "Ipoh", "Shah Alam", "Seremban", "Johor Bahru" }));
        getContentPane().add(addressComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 140, -1));

        customerIDFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        customerIDFld.setEnabled(false);
        getContentPane().add(customerIDFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 140, -1));

        contactTxtFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        getContentPane().add(contactTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 140, -1));

        usernameTxtFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        usernameTxtFld.setEnabled(false);
        getContentPane().add(usernameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 140, -1));

        emailTxtFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        getContentPane().add(emailTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 140, -1));

        showPasswordcheckBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        showPasswordcheckBox.setText("show");
        showPasswordcheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordcheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(showPasswordcheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 70, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFldActionPerformed

    private void newPassFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassFldActionPerformed

    private void confirmPassFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFldActionPerformed

    private void updateDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsBtnActionPerformed
        String name = usernameTxtFld.getText();
        String email = emailTxtFld.getText();
        String address = addressComboBox.getSelectedItem().toString();
        String confirmPassword = confirmPassFld.getText();
        String newPassword = newPassFld.getText();
        String contact = contactTxtFld.getText();
        
        
       //validateRegisterDetails is used but performs similar functionality 
       boolean validDetails = loggedCustomer.validateUpdateDetails(name,email,address,newPassword,confirmPassword,contact);
       if(validDetails){
            try {
                updatedCustomer.setName(name);
                updatedCustomer.setEmail(email);
                updatedCustomer.setAddress(address);
                updatedCustomer.setContact(contact);
                if(newPassword.equals("") || confirmPassword.equals("")){
                    updatedCustomer.setPassword(loggedCustomer.getPassword());
                    
                }
                else{
                    updatedCustomer.setPassword(newPassword);
                }
                loggedCustomer.updateProfile(loggedCustomer, updatedCustomer);
            } catch (IOException ex) {
                Logger.getLogger(CustomerAccountSettings.class.getName()).log(Level.SEVERE, null, ex);
            }
           JOptionPane.showMessageDialog(null, "The application will Restart to finalize changes","Restart Required", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            System.gc();
            Window win [] = Window.getWindows();
            for (Window win1 : win) {
                win1.dispose();
            }
            MainPageView newFrame = new MainPageView();
           newFrame.setVisible(true);
       }
       
    }//GEN-LAST:event_updateDetailsBtnActionPerformed

    private void showPasswordcheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordcheckBoxActionPerformed
        if(showPasswordcheckBox.isSelected()){
            passFld.setEchoChar((char)0);
            newPassFld.setEchoChar((char)0);
            confirmPassFld.setEchoChar((char)0);
        }
        else{
            passFld.setEchoChar('*');
            newPassFld.setEchoChar('*');
            confirmPassFld.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordcheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewPassLbl;
    private javax.swing.JSeparator SettingsSep;
    private javax.swing.JComboBox<String> addressComboBox;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JPasswordField confirmPassFld;
    private javax.swing.JLabel conformPassLbl;
    private javax.swing.JLabel contactNumberLbl;
    private javax.swing.JTextField contactTxtFld;
    private javax.swing.JLabel csutomerIdLbl;
    private javax.swing.JTextField customerIDFld;
    private javax.swing.JLabel customerNameLbl;
    private javax.swing.JLabel customerSettingsIcon;
    private javax.swing.JPanel customerSettingsUpPanel;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtFld;
    private javax.swing.JPasswordField newPassFld;
    private javax.swing.JPasswordField passFld;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel profileSettingsLbl;
    private javax.swing.JCheckBox showPasswordcheckBox;
    private javax.swing.JButton updateDetailsBtn;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxtFld;
    // End of variables declaration//GEN-END:variables
}
