/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.Administrator;
import Controller.Customer;
import Controller.User;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * 
 */
@SuppressWarnings("serial")
public class Login extends javax.swing.JFrame {

    public Login() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
        initComponents();


    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInPanel = new javax.swing.JPanel();
        registerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        passwordSeparator = new javax.swing.JSeparator();
        signInLbl = new javax.swing.JLabel();
        signIncurveLabel = new javax.swing.JLabel();
        loginLbl = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        usernameTextFid = new javax.swing.JTextField();
        passwordTxtFld = new javax.swing.JPasswordField();
        passwordTxt = new javax.swing.JLabel();
        usernameSeparator = new javax.swing.JSeparator();
        usernameLbl = new javax.swing.JLabel();
        showPasswordcheckBox = new javax.swing.JCheckBox();
        forgotPasswordLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInPanel.setBackground(new java.awt.Color(255, 255, 255));
        signInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerBtn.setBackground(new java.awt.Color(80, 35, 108));
        registerBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setBorder(null);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        signInPanel.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 90, -1));

        backBtn.setBackground(new java.awt.Color(80, 35, 108));
        backBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8_Go_Back_24px.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setToolTipText("");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        signInPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));
        signInPanel.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 220, 20));

        signInLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        signInLbl.setForeground(new java.awt.Color(255, 102, 0));
        signInLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-customer-48.png"))); // NOI18N
        signInLbl.setText("Sign In");
        signInLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInLbl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        signInPanel.add(signInLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, 80));

        signIncurveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signIncurveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/logtheme.PNG"))); // NOI18N
        signInPanel.add(signIncurveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -80, 740, 380));

        loginLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLbl.setText("Login");
        signInPanel.add(loginLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 70, -1));

        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/btncurve.PNG"))); // NOI18N
        LoginButton.setBorder(null);
        LoginButton.setBorderPainted(false);
        LoginButton.setContentAreaFilled(false);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        signInPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 290, 40));

        usernameTextFid.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        usernameTextFid.setBorder(null);
        usernameTextFid.setOpaque(false);
        signInPanel.add(usernameTextFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 220, 30));

        passwordTxtFld.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        passwordTxtFld.setBorder(null);
        passwordTxtFld.setOpaque(false);
        passwordTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtFldActionPerformed(evt);
            }
        });
        signInPanel.add(passwordTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 220, 30));

        passwordTxt.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        passwordTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordTxt.setText("Password");
        signInPanel.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, 50));
        signInPanel.add(usernameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 220, 10));

        usernameLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        usernameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLbl.setText("Username");
        signInPanel.add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 50));

        showPasswordcheckBox.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordcheckBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        showPasswordcheckBox.setText("show");
        showPasswordcheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordcheckBoxActionPerformed(evt);
            }
        });
        signInPanel.add(showPasswordcheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 70, 30));

        forgotPasswordLbl.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        forgotPasswordLbl.setForeground(new java.awt.Color(255, 0, 51));
        forgotPasswordLbl.setText("Forgot Password ?");
        forgotPasswordLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLblMouseClicked(evt);
            }
        });
        signInPanel.add(forgotPasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        getContentPane().add(signInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 640));

        setSize(new java.awt.Dimension(432, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //use these variables throughout
    private User userC = new User();
    private Administrator admin = new Administrator();
    private Customer loggedCustomer = new Customer();
  
    
    @SuppressWarnings("deprecation")
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        
        try {
            //if statement for admin trying to login
             if(admin.verifyLogin(usernameTextFid.getText() , passwordTxtFld.getText())) {
                AdminPanel adminPanel = new AdminPanel();
                this.dispose();
                adminPanel.setVisible(true);
                adminPanel.pack();
            }
            //if any customers tries to login
             else   if( userC.verifyLogin(usernameTextFid.getText() , passwordTxtFld.getText())) {
                 loggedCustomer = userC.getCurrentCustomer();
                 MainPageView nextFrame = new MainPageView(loggedCustomer);
                 this.dispose();
                nextFrame.setVisible(true);
               //nextFrame.repaint();
               // nextFrame.revalidate();
            }

             else{
                JOptionPane.showMessageDialog(null, "Please insert the correct Login credentials!", "Login Failed", JOptionPane.ERROR_MESSAGE);
             }


        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void passwordTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtFldActionPerformed

    private void showPasswordcheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordcheckBoxActionPerformed
        if(showPasswordcheckBox.isSelected()){
            passwordTxtFld.setEchoChar((char)0);
        }
        else{
            passwordTxtFld.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordcheckBoxActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        this.dispose();
        Register registerFrame = new Register();
         registerFrame.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        MainPageView newFrame = new MainPageView();
          newFrame.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void forgotPasswordLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLblMouseClicked
        ForgotPassword forgotPasswordFrame = new ForgotPassword();
        forgotPasswordFrame.setVisible(true);
    }//GEN-LAST:event_forgotPasswordLblMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel forgotPasswordLbl;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JLabel passwordTxt;
    private javax.swing.JPasswordField passwordTxtFld;
    private javax.swing.JButton registerBtn;
    private javax.swing.JCheckBox showPasswordcheckBox;
    private javax.swing.JLabel signInLbl;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JLabel signIncurveLabel;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JSeparator usernameSeparator;
    private javax.swing.JTextField usernameTextFid;
    // End of variables declaration//GEN-END:variables
}
