/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Product;
import java.awt.Image;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AbdelRahman Badran , Madoma Diallo 
 */
@SuppressWarnings("serial")
public class ProductInfo extends javax.swing.JFrame {
    
    private static ArrayList<Product> cartItems = new ArrayList<>();

    public static ArrayList<Product> getCartItems() {
        return cartItems;
    }
    
    private Product currentProduct;

    /**
     * Creates new form ProductInfo
     * @param selectedProduct
     */
    
    
    public ProductInfo(Product selectedProduct ) {
            this.currentProduct = selectedProduct;
            
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>  
          
        initComponents();
        
        nameTxtFld.setText(selectedProduct.getName());
        featuresTextArea.setText(selectedProduct.getDescription());
        priceTxtFld.setText(Double.toString(selectedProduct.getPrice()));
        categoryTxtFld.setText(selectedProduct.getCategory().toString());
        stockTxtFld.setText(Integer.toString(selectedProduct.getQuantity()));
        ratingTxtFld.setText(Integer.toString(selectedProduct.getRating()));
        packagingTxtFld.setText(selectedProduct.getPackaging());
        productImage.setIcon(loadImage());
             
        

      
    }

    ProductInfo() {
          initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        addToCartBtn = new javax.swing.JButton();
        priceLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        packagingLbl = new javax.swing.JLabel();
        productImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        featuresTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        increaseQuantityBtn = new javax.swing.JButton();
        decreaseQuantityBtn = new javax.swing.JButton();
        itemNumberFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ratingLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JTextField();
        categoryTxtFld = new javax.swing.JTextField();
        ratingTxtFld = new javax.swing.JTextField();
        priceTxtFld = new javax.swing.JTextField();
        stockTxtFld = new javax.swing.JTextField();
        categoryLbl = new javax.swing.JLabel();
        packagingTxtFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8-info-40.png"))); // NOI18N
        jLabel1.setText("Product Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 80));

        jPanel3.setEnabled(false);

        nameLbl.setText("Product Name:");

        addToCartBtn.setBackground(new java.awt.Color(0, 204, 102));
        addToCartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/icons8_Add_Shopping_Cart_24px.png"))); // NOI18N
        addToCartBtn.setText("Add To Cart");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });

        priceLbl.setText("Price:");

        stockLbl.setText("Stock:");

        packagingLbl.setText("Packaging:");

        featuresTextArea.setColumns(20);
        featuresTextArea.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        featuresTextArea.setLineWrap(true);
        featuresTextArea.setRows(5);
        featuresTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        featuresTextArea.setEnabled(false);
        jScrollPane1.setViewportView(featuresTextArea);

        jLabel8.setText("Quantity");

        increaseQuantityBtn.setText("+");
        increaseQuantityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseQuantityBtnActionPerformed(evt);
            }
        });

        decreaseQuantityBtn.setText("-");
        decreaseQuantityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseQuantityBtnActionPerformed(evt);
            }
        });

        itemNumberFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemNumberFld.setText("1");

        jLabel7.setText("Description");

        ratingLbl.setText("Rating:");

        nameTxtFld.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        nameTxtFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nameTxtFld.setEnabled(false);

        categoryTxtFld.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        categoryTxtFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        categoryTxtFld.setEnabled(false);

        ratingTxtFld.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        ratingTxtFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ratingTxtFld.setEnabled(false);

        priceTxtFld.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        priceTxtFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        priceTxtFld.setEnabled(false);

        stockTxtFld.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        stockTxtFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        stockTxtFld.setEnabled(false);

        categoryLbl.setText("Category:");

        packagingTxtFld.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        packagingTxtFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        packagingTxtFld.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addToCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(decreaseQuantityBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(itemNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(increaseQuantityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLbl)
                                    .addComponent(priceLbl)
                                    .addComponent(ratingLbl)
                                    .addComponent(stockLbl)
                                    .addComponent(categoryLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stockTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(ratingTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(priceTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(categoryTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(nameTxtFld)
                                    .addComponent(packagingTxtFld)))
                            .addComponent(packagingLbl))
                        .addGap(38, 38, 38)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {decreaseQuantityBtn, increaseQuantityBtn});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(decreaseQuantityBtn)
                                .addComponent(itemNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(increaseQuantityBtn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLbl)
                                    .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceLbl)
                                    .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stockLbl)
                                    .addComponent(stockTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(categoryTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ratingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ratingTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(packagingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packagingTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35)
                .addComponent(addToCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {decreaseQuantityBtn, increaseQuantityBtn});

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 920, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void increaseQuantityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQuantityBtnActionPerformed
        int quantityofOrder = Integer.parseInt( itemNumberFld.getText());
        itemNumberFld.setText(String.valueOf(++quantityofOrder));
    }//GEN-LAST:event_increaseQuantityBtnActionPerformed

    private void decreaseQuantityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQuantityBtnActionPerformed
       int quantityofOrder = Integer.parseInt( itemNumberFld.getText());
        itemNumberFld.setText(String.valueOf(--quantityofOrder));
    }//GEN-LAST:event_decreaseQuantityBtnActionPerformed

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        if(Integer.parseInt(stockTxtFld.getText()) < Integer.parseInt(itemNumberFld.getText()) ) {
            JOptionPane.showMessageDialog(null, "Not enough product in Stock!");
        }
        else{
            int quantity = Integer.parseInt(itemNumberFld.getText());
            Product product = new Product(currentProduct.getName(),currentProduct.getPrice(),currentProduct.getPackaging(),quantity);
            cartItems.add(product);
             JOptionPane.showMessageDialog(null, "Product added to cart!");
             this.dispose();
            //decrease stock of ordered product
        }
    }//GEN-LAST:event_addToCartBtnActionPerformed
    public ImageIcon loadImage(){
        Path path = Paths.get(currentProduct.getImage());
                //path.subpath(1, 3);
                String truncatedPath = path.toString();
                
                String newPath = truncatedPath.replaceAll("\\\\", "/");
                ImageIcon icn = new ImageIcon(getClass().getResource(newPath));
                Image img = icn.getImage().getScaledInstance(productImage.getWidth(), productImage.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                return icon;
    }
    
    
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JTextField categoryTxtFld;
    private javax.swing.JButton decreaseQuantityBtn;
    private javax.swing.JTextArea featuresTextArea;
    private javax.swing.JButton increaseQuantityBtn;
    private javax.swing.JTextField itemNumberFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JLabel packagingLbl;
    private javax.swing.JTextField packagingTxtFld;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxtFld;
    private javax.swing.JLabel productImage;
    private javax.swing.JLabel ratingLbl;
    private javax.swing.JTextField ratingTxtFld;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTxtFld;
    // End of variables declaration//GEN-END:variables
}
